### ISSUE TITLE
Add an app icon

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#16]
It's requirement for publishing the app to AppCenter.

@Fatih20 Sorry to bother you, but would you mind creating a set of icons for this app?

**Comment by Fatih20** [comment]
Sure, do be patient though.

**Comment by Fatih20** [comment]
@ryonakano You haven't told me how the app icon should be named and placed directory wise.

**Comment by Fatih20** [comment]
Alright, I have some ideas about the icons.

- A photo (or photos) just like the elementaryOS photo viewer minus the camera lens
- A photo album, either just the cover or actually opened. Examples below
https://www.flaticon.com/free-icon/photo-album_2793830
https://www.flaticon.com/premium-icon/photo-album_1702337
- Polaroid or a collections of polaroid. Example below.
https://www.flaticon.com/free-icon/photo_529259?term=polaroid&page=1&position=43&page=1&position=43&related_id=529259&origin=search

I may not use your input but I want to know your opinion because you're more familiar with the app.
@ryonakano @aharotias2

**Comment by aharotias2** [comment]
Hi, @Fatih20 
I think the third icon is a good choice.
because it’s simple. simple and lightweight is a policy of this app.
book style seems heavy.
Thank you for your idea.

**Comment by Fatih20** [comment]
> Hi, @Fatih20
> I think the third icon is a good choice.
> because it’s simple. simple and lightweight is a policy of this app.
> book style seems heavy.
> Thank you for your idea.

So you'd prefer the polaroid?

> * Polaroid or a collections of polaroid. Example below.
>   https://www.flaticon.com/free-icon/photo_529259?term=polaroid&page=1&position=43&page=1&position=43&related_id=529259&origin=search

**Comment by aharotias2** [comment]
@Fatih20
Yes!

**Comment by aharotias2** [comment]
@Fatih20 
I have merged your pull request.
Thank you for your good work.

**Comment by ryonakano** [comment]
Fixed in 0c7943207ed044c4197b21f772785ff7da638ea1
